# Test coverage
name: TestCov

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
    
  workflow_dispatch:
    inputs:
      deployment_context:
        description: 'Deployment context'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - testing
        - prod
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # This library is most-commonly run on 32-bit targets. So we need to put together
    #   a GCC environment that supports it.
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x86
    - name: Install tools
      run: sudo apt install -y cppcheck lcov 
    - name: make
      run: |
        echo "Tags: $TAGS"
        echo "Environment: $ENVIRONMENT"    
        cd extras/unit_tests; make coverage check
    - uses: actions/upload-artifact@v4
      with:
        name: results
        path: |
          extras/unit_tests/build 
        if-no-files-found: error
        compression-level: 7
        overwrite: false
        include-hidden-files: true


#name: DocGen
#on:
#  workflow_run:
#    workflows: [ "TestCov" ]
#    label:
#      types: [completed]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Install tools
#      run: sudo apt install -y graphviz doxygen
#    - name: build-doc
#      run: doxygen Doxyfile
#    - uses: actions/upload-artifact@v4
#      with:
#        name: results
#        path: |
#          extras/doc/doxygen
#        if-no-files-found: error
#        compression-level: 8
#        overwrite: false
#        include-hidden-files: true
